{"totalCount":8,"grade":"D","repositories":[{"url":"https://github.com/MTES-MCT/acceslibre","vulnerabilityAlerts":{"totalCount":8,"nodes":[{"dismissedAt":null,"createdAt":"2024-07-10T21:59:58Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qg2p-9jwr-mmqf"},{"type":"CVE","value":"CVE-2024-38875"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-38875"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/7285644640f085f41d60ab0c8ae4e9153f0485db"},{"url":"https://github.com/django/django/commit/79f368764295df109a37192f6182fb6f361d85b5"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-56.yaml"},{"url":"https://github.com/advisories/GHSA-qg2p-9jwr-mmqf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:00:45Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9jmf-237g-qf46"},{"type":"CVE","value":"CVE-2024-39330"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39330"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/2b00edc0151a660d1eb86da4059904a0fc4e095e"},{"url":"https://github.com/django/django/commit/9f4f63e9ebb7bf6cb9547ee4e2526b9b96703270"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-58.yaml"},{"url":"https://github.com/advisories/GHSA-9jmf-237g-qf46"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:01:04Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-x7q2-wr7g-xqmf"},{"type":"CVE","value":"CVE-2024-39329"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39329"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/07cefdee4a9d1fcd9a3a631cbd07c78defd1923b"},{"url":"https://github.com/django/django/commit/156d3186c96e3ec2ca73b8b25dc2ef366e38df14"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-57.yaml"},{"url":"https://github.com/advisories/GHSA-x7q2-wr7g-xqmf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:02:11Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-f6f8-9mx6-9mx2"},{"type":"CVE","value":"CVE-2024-39614"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39614"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3"},{"url":"https://github.com/django/django/commit/8e7a44e4bec0f11474699c3111a5e0a45afe7f49"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-59.yaml"},{"url":"https://github.com/advisories/GHSA-f6f8-9mx6-9mx2"}]}}},{"dismissedAt":null,"createdAt":"2024-07-12T08:55:55Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qg2p-9jwr-mmqf"},{"type":"CVE","value":"CVE-2024-38875"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-38875"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/7285644640f085f41d60ab0c8ae4e9153f0485db"},{"url":"https://github.com/django/django/commit/79f368764295df109a37192f6182fb6f361d85b5"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-56.yaml"},{"url":"https://github.com/advisories/GHSA-qg2p-9jwr-mmqf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-12T08:55:55Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9jmf-237g-qf46"},{"type":"CVE","value":"CVE-2024-39330"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39330"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/2b00edc0151a660d1eb86da4059904a0fc4e095e"},{"url":"https://github.com/django/django/commit/9f4f63e9ebb7bf6cb9547ee4e2526b9b96703270"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-58.yaml"},{"url":"https://github.com/advisories/GHSA-9jmf-237g-qf46"}]}}},{"dismissedAt":null,"createdAt":"2024-07-12T08:55:55Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-x7q2-wr7g-xqmf"},{"type":"CVE","value":"CVE-2024-39329"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39329"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/07cefdee4a9d1fcd9a3a631cbd07c78defd1923b"},{"url":"https://github.com/django/django/commit/156d3186c96e3ec2ca73b8b25dc2ef366e38df14"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-57.yaml"},{"url":"https://github.com/advisories/GHSA-x7q2-wr7g-xqmf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-12T08:55:55Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-f6f8-9mx6-9mx2"},{"type":"CVE","value":"CVE-2024-39614"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39614"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3"},{"url":"https://github.com/django/django/commit/8e7a44e4bec0f11474699c3111a5e0a45afe7f49"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-59.yaml"},{"url":"https://github.com/advisories/GHSA-f6f8-9mx6-9mx2"}]}}}]},"grade":"D"}]}