{"totalCount":11,"grade":"D","repositories":[{"url":"https://github.com/MTES-MCT/acceslibre","vulnerabilityAlerts":{"totalCount":11,"nodes":[{"dismissedAt":null,"createdAt":"2023-07-25T20:01:28Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"django-rest-framework"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-xqcf-hj92-967m"},{"type":"CVE","value":"CVE-2018-25045"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2018-25045"},{"url":"https://github.com/encode/django-rest-framework/pull/6191"},{"url":"https://github.com/encode/django-rest-framework/pull/6330"},{"url":"https://github.com/encode/django-rest-framework/commit/4bb9a3c48427867ef1e46f7dee945a4c25a4f9b8"},{"url":"https://github.com/advisories/GHSA-xqcf-hj92-967m"}]}}},{"dismissedAt":null,"createdAt":"2023-11-02T21:47:40Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qmf9-6jqf-j8fq"},{"type":"CVE","value":"CVE-2023-46695"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-46695"},{"url":"https://docs.djangoproject.com/en/4.2/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2023/nov/01/security-releases/"},{"url":"https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f"},{"url":"https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e"},{"url":"https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://security.netapp.com/advisory/ntap-20231214-0001/"},{"url":"https://github.com/advisories/GHSA-qmf9-6jqf-j8fq"}]}}},{"dismissedAt":null,"createdAt":"2023-11-03T19:54:17Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-7h4p-27mh-hmrw"},{"type":"CVE","value":"CVE-2023-41164"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-41164"},{"url":"https://docs.djangoproject.com/en/4.2/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2023/sep/04/security-releases/"},{"url":"https://github.com/django/django/commit/6f030b1149bd8fa4ba90452e77cb3edc095ce54e"},{"url":"https://github.com/django/django/commit/9c51b4dcfa0cefcb48231f4d71cafa80821f87b9"},{"url":"https://github.com/django/django/commit/ba00bc5ec6a7eff5e08be438f7b5b0e9574e8ff0"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-225.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HJFRPUHDYJHBH3KYHSPGULQM4JN7BMSU/"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HJFRPUHDYJHBH3KYHSPGULQM4JN7BMSU/"},{"url":"https://security.netapp.com/advisory/ntap-20231214-0002/"},{"url":"https://github.com/advisories/GHSA-7h4p-27mh-hmrw"}]}}},{"dismissedAt":null,"createdAt":"2023-11-03T19:57:05Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-h8gc-pgj2-vjm3"},{"type":"CVE","value":"CVE-2023-43665"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-43665"},{"url":"https://docs.djangoproject.com/en/4.2/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2023/oct/04/security-releases/"},{"url":"https://github.com/django/django/commit/be9c27c4d18c2e6a5be8af4e53c0797440794473"},{"url":"https://github.com/django/django/commit/c7b7024742250414e426ad49fb80db943e7ba4e8"},{"url":"https://github.com/django/django/commit/ccdade1a0262537868d7ca64374de3d957ca50c5"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-226.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HJFRPUHDYJHBH3KYHSPGULQM4JN7BMSU/"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HJFRPUHDYJHBH3KYHSPGULQM4JN7BMSU/"},{"url":"https://github.com/advisories/GHSA-h8gc-pgj2-vjm3"}]}}},{"dismissedAt":null,"createdAt":"2023-11-06T09:42:35Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qmf9-6jqf-j8fq"},{"type":"CVE","value":"CVE-2023-46695"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-46695"},{"url":"https://docs.djangoproject.com/en/4.2/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2023/nov/01/security-releases/"},{"url":"https://github.com/django/django/commit/048a9ebb6ea468426cb4e57c71572cbbd975517f"},{"url":"https://github.com/django/django/commit/4965bfdde2e5a5c883685019e57d123a3368a75e"},{"url":"https://github.com/django/django/commit/f9a7fb8466a7ba4857eaf930099b5258f3eafb2b"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-222.yaml"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://security.netapp.com/advisory/ntap-20231214-0001/"},{"url":"https://github.com/advisories/GHSA-qmf9-6jqf-j8fq"}]}}},{"dismissedAt":null,"createdAt":"2023-11-06T09:42:35Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-7h4p-27mh-hmrw"},{"type":"CVE","value":"CVE-2023-41164"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-41164"},{"url":"https://docs.djangoproject.com/en/4.2/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2023/sep/04/security-releases/"},{"url":"https://github.com/django/django/commit/6f030b1149bd8fa4ba90452e77cb3edc095ce54e"},{"url":"https://github.com/django/django/commit/9c51b4dcfa0cefcb48231f4d71cafa80821f87b9"},{"url":"https://github.com/django/django/commit/ba00bc5ec6a7eff5e08be438f7b5b0e9574e8ff0"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-225.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HJFRPUHDYJHBH3KYHSPGULQM4JN7BMSU/"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HJFRPUHDYJHBH3KYHSPGULQM4JN7BMSU/"},{"url":"https://security.netapp.com/advisory/ntap-20231214-0002/"},{"url":"https://github.com/advisories/GHSA-7h4p-27mh-hmrw"}]}}},{"dismissedAt":null,"createdAt":"2023-11-06T09:42:35Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-h8gc-pgj2-vjm3"},{"type":"CVE","value":"CVE-2023-43665"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-43665"},{"url":"https://docs.djangoproject.com/en/4.2/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2023/oct/04/security-releases/"},{"url":"https://github.com/django/django/commit/be9c27c4d18c2e6a5be8af4e53c0797440794473"},{"url":"https://github.com/django/django/commit/c7b7024742250414e426ad49fb80db943e7ba4e8"},{"url":"https://github.com/django/django/commit/ccdade1a0262537868d7ca64374de3d957ca50c5"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-226.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HJFRPUHDYJHBH3KYHSPGULQM4JN7BMSU/"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HJFRPUHDYJHBH3KYHSPGULQM4JN7BMSU/"},{"url":"https://github.com/advisories/GHSA-h8gc-pgj2-vjm3"}]}}},{"dismissedAt":null,"createdAt":"2024-02-07T17:57:04Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-xxj9-f6rv-m3x4"},{"type":"CVE","value":"CVE-2024-24680"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-24680"},{"url":"https://docs.djangoproject.com/en/5.0/releases/security/"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/feb/06/security-releases/"},{"url":"https://github.com/django/django/commit/16a8fe18a3b81250f4fa57e3f93f0599dc4895bc"},{"url":"https://github.com/django/django/commit/55519d6cf8998fe4c8f5c8abffc2b10a7c3d14e9"},{"url":"https://github.com/django/django/commit/572ea07e84b38ea8de0551f4b4eda685d91d09d2"},{"url":"https://github.com/django/django/commit/c1171ffbd570db90ca206c30f8e2b9f691243820"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-28.yaml"},{"url":"https://github.com/advisories/GHSA-xxj9-f6rv-m3x4"}]}}},{"dismissedAt":null,"createdAt":"2024-02-12T10:12:24Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-xxj9-f6rv-m3x4"},{"type":"CVE","value":"CVE-2024-24680"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-24680"},{"url":"https://docs.djangoproject.com/en/5.0/releases/security/"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/feb/06/security-releases/"},{"url":"https://github.com/django/django/commit/16a8fe18a3b81250f4fa57e3f93f0599dc4895bc"},{"url":"https://github.com/django/django/commit/55519d6cf8998fe4c8f5c8abffc2b10a7c3d14e9"},{"url":"https://github.com/django/django/commit/572ea07e84b38ea8de0551f4b4eda685d91d09d2"},{"url":"https://github.com/django/django/commit/c1171ffbd570db90ca206c30f8e2b9f691243820"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-28.yaml"},{"url":"https://github.com/advisories/GHSA-xxj9-f6rv-m3x4"}]}}},{"dismissedAt":null,"createdAt":"2024-03-18T21:02:28Z","securityVulnerability":{"severity":"LOW","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-vm8q-m57g-pff3"},{"type":"CVE","value":"CVE-2024-27351"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-27351"},{"url":"https://docs.djangoproject.com/en/5.0/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/mar/04/security-releases"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-47.yaml"},{"url":"https://github.com/advisories/GHSA-vm8q-m57g-pff3"}]}}},{"dismissedAt":null,"createdAt":"2024-03-25T09:38:42Z","securityVulnerability":{"severity":"LOW","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-vm8q-m57g-pff3"},{"type":"CVE","value":"CVE-2024-27351"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-27351"},{"url":"https://docs.djangoproject.com/en/5.0/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/mar/04/security-releases"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-47.yaml"},{"url":"https://github.com/advisories/GHSA-vm8q-m57g-pff3"}]}}}]},"grade":"D"}]}