{"totalCount":6,"grade":"D","repositories":[{"url":"https://github.com/MTES-MCT/carbure","vulnerabilityAlerts":{"totalCount":6,"nodes":[{"dismissedAt":null,"createdAt":"2021-06-23T07:34:32Z","securityVulnerability":{"severity":"LOW","package":{"name":"aiohttp"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-v6wp-4m6f-gcjg"},{"type":"CVE","value":"CVE-2021-21330"}],"references":[{"url":"https://github.com/aio-libs/aiohttp/security/advisories/GHSA-v6wp-4m6f-gcjg"},{"url":"https://github.com/aio-libs/aiohttp/commit/2545222a3853e31ace15d87ae0e2effb7da0c96b"},{"url":"https://github.com/aio-libs/aiohttp/blob/master/CHANGES.rst#374-2021-02-25"},{"url":"https://pypi.org/project/aiohttp/"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-21330"},{"url":"https://www.debian.org/security/2021/dsa-4864"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JN3V7CZJRT4QFCVXB6LDPCJH7NAOFCA5/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FU7ENI54JNEK3PHEFGCE46DGMFNTVU6L/"},{"url":"https://github.com/advisories/GHSA-v6wp-4m6f-gcjg"}]}}},{"dismissedAt":null,"createdAt":"2022-01-23T17:22:51Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"numpy"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-6p56-wp2h-9hxr"},{"type":"CVE","value":"CVE-2021-33430"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-33430"},{"url":"https://github.com/numpy/numpy/issues/18939"},{"url":"https://github.com/numpy/numpy/commit/ae317fd9ff3e79c0eac357d723bfc29cbd625f2e"},{"url":"https://github.com/advisories/GHSA-6p56-wp2h-9hxr"}]}}},{"dismissedAt":null,"createdAt":"2022-01-23T17:22:51Z","securityVulnerability":{"severity":"LOW","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jrh2-hc4r-7jwx"},{"type":"CVE","value":"CVE-2021-45452"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-45452"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"},{"url":"https://github.com/advisories/GHSA-jrh2-hc4r-7jwx"}]}}},{"dismissedAt":null,"createdAt":"2022-01-23T17:22:51Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-53qw-q765-4fww"},{"type":"CVE","value":"CVE-2021-45115"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-45115"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"},{"url":"https://github.com/advisories/GHSA-53qw-q765-4fww"}]}}},{"dismissedAt":null,"createdAt":"2022-01-23T17:22:51Z","securityVulnerability":{"severity":"LOW","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8c5j-9r9f-c6w8"},{"type":"CVE","value":"CVE-2021-45116"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-45116"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"},{"url":"https://github.com/advisories/GHSA-8c5j-9r9f-c6w8"}]}}},{"dismissedAt":null,"createdAt":"2022-01-23T17:22:51Z","securityVulnerability":{"severity":"HIGH","package":{"name":"node-fetch"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-r683-j2x4-v87g"},{"type":"CVE","value":"CVE-2022-0235"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-0235"},{"url":"https://github.com/node-fetch/node-fetch/commit/36e47e8a6406185921e4985dcbeff140d73eaa10"},{"url":"https://huntr.dev/bounties/d26ab655-38d6-48b3-be15-f9ad6b6ae6f7"},{"url":"https://github.com/node-fetch/node-fetch/pull/1453"},{"url":"https://github.com/advisories/GHSA-r683-j2x4-v87g"}]}}}]},"grade":"D"}]}