{"totalCount":4,"grade":"E","repositories":[null,null,{"url":"https://github.com/MTES-MCT/adock-api","vulnerabilityAlerts":{"totalCount":4,"nodes":[{"dismissedAt":null,"createdAt":"2021-09-22T19:22:31Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-xpfp-f569-q3p2"},{"type":"CVE","value":"CVE-2021-35042"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-35042"},{"url":"https://docs.djangoproject.com/en/3.2/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2021/jul/01/security-releases/"},{"url":"https://www.openwall.com/lists/oss-security/2021/07/02/2"},{"url":"https://security.netapp.com/advisory/ntap-20210805-0008/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SS6NJTBYWOX6J7G4U3LUOILARJKWPQ5Y/"},{"url":"https://github.com/django/django/commit/0bd57a879a0d54920bb9038a732645fb917040e9"},{"url":"https://github.com/advisories/GHSA-xpfp-f569-q3p2"}]}}},{"dismissedAt":null,"createdAt":"2022-09-20T22:04:49Z","securityVulnerability":{"severity":"HIGH","package":{"name":"urllib3"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-q2q7-5pp4-w6pg"},{"type":"CVE","value":"CVE-2021-33503"}],"references":[{"url":"https://github.com/urllib3/urllib3/security/advisories/GHSA-q2q7-5pp4-w6pg"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-33503"},{"url":"https://github.com/urllib3/urllib3/commit/2d4a3fee6de2fa45eb82169361918f759269b4ec"},{"url":"https://github.com/advisories/GHSA-q2q7-5pp4-w6pg"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FMUGWEAUYGGHTPPXT6YBD53WYXQGVV73/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6SCV7ZNAHS3E6PBFLJGENCDRDRWRZZ6W/"},{"url":"https://security.gentoo.org/glsa/202107-36"},{"url":"https://www.oracle.com/security-alerts/cpuoct2021.html"},{"url":"https://github.com/urllib3/urllib3/commit/5b047b645f5f93900d5e2fc31230848c25eb1f5f#diff-52026d639119bf1e0364836b4e8a18bd9ed3c95c6ba39b26534a5057a65e35bbR65"}]}}},{"dismissedAt":null,"createdAt":"2023-03-21T22:35:35Z","securityVulnerability":{"severity":"HIGH","package":{"name":"sentry-sdk"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-29pr-6jr8-q5jm"},{"type":"CVE","value":"CVE-2023-28117"}],"references":[{"url":"https://github.com/getsentry/sentry-python/security/advisories/GHSA-29pr-6jr8-q5jm"},{"url":"https://github.com/getsentry/sentry-python/pull/1842"},{"url":"https://github.com/getsentry/sentry-python/releases/tag/1.14.0"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-28117"},{"url":"https://github.com/advisories/GHSA-29pr-6jr8-q5jm"}]}}},{"dismissedAt":null,"createdAt":"2023-05-23T00:07:32Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"requests"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-j8r2-6x86-q33q"},{"type":"CVE","value":"CVE-2023-32681"}],"references":[{"url":"https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q"},{"url":"https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-32681"},{"url":"https://github.com/psf/requests/releases/tag/v2.31.0"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/"},{"url":"https://github.com/advisories/GHSA-j8r2-6x86-q33q"}]}}}]},"grade":"E"}]}