{"totalCount":25,"grade":"E","repositories":[{"url":"https://github.com/MTES-MCT/envergo","vulnerabilityAlerts":{"totalCount":25,"nodes":[{"dismissedAt":null,"createdAt":"2021-07-06T13:16:03Z","securityVulnerability":{"severity":"HIGH","package":{"name":"trim-newlines"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-7p7h-4mm5-852v"},{"type":"CVE","value":"CVE-2021-33623"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-33623"},{"url":"https://github.com/sindresorhus/trim-newlines/commit/25246c6ce5eea1c82d448998733a6302a4350d91"},{"url":"https://github.com/sindresorhus/trim-newlines/releases/tag/v4.0.1"},{"url":"https://www.npmjs.com/package/trim-newlines"},{"url":"https://security.netapp.com/advisory/ntap-20210702-0007/"},{"url":"https://github.com/advisories/GHSA-7p7h-4mm5-852v"}]}}},{"dismissedAt":null,"createdAt":"2021-09-21T02:08:00Z","securityVulnerability":{"severity":"HIGH","package":{"name":"semver-regex"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-44c6-4v22-4mhx"},{"type":"CVE","value":"CVE-2021-3795"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-3795"},{"url":"https://github.com/sindresorhus/semver-regex/commit/11c66245f4e1976dccc52977ed183696a21a3fd7"},{"url":"https://huntr.dev/bounties/006624e3-35ac-448f-aab9-7b5183f30e28"},{"url":"https://github.com/advisories/GHSA-44c6-4v22-4mhx"}]}}},{"dismissedAt":null,"createdAt":"2021-09-22T23:45:47Z","securityVulnerability":{"severity":"HIGH","package":{"name":"nth-check"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-rp65-9cf3-cjxr"},{"type":"CVE","value":"CVE-2021-3803"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-3803"},{"url":"https://github.com/fb55/nth-check/commit/9894c1d2010870c351f66c6f6efcf656e26bb726"},{"url":"https://huntr.dev/bounties/8cf8cc06-d2cf-4b4e-b42c-99fafb0b04d0"},{"url":"https://github.com/advisories/GHSA-rp65-9cf3-cjxr"}]}}},{"dismissedAt":null,"createdAt":"2022-01-31T09:03:47Z","securityVulnerability":{"severity":"HIGH","package":{"name":"glob-parent"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-ww39-953v-wcq6"},{"type":"CVE","value":"CVE-2020-28469"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2020-28469"},{"url":"https://github.com/gulpjs/glob-parent/pull/36"},{"url":"https://github.com/gulpjs/glob-parent/blob/6ce8d11f2f1ed8e80a9526b1dc8cf3aa71f43474/index.js%23L9"},{"url":"https://github.com/gulpjs/glob-parent/releases/tag/v5.1.2"},{"url":"https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSBOWERGITHUBES128-1059093"},{"url":"https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-1059092"},{"url":"https://snyk.io/vuln/SNYK-JS-GLOBPARENT-1016905"},{"url":"https://www.oracle.com/security-alerts/cpujan2022.html"},{"url":"https://github.com/advisories/GHSA-ww39-953v-wcq6"}]}}},{"dismissedAt":null,"createdAt":"2022-03-12T00:36:36Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Pillow"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9j59-75qj-795w"},{"type":"CVE","value":"CVE-2022-24303"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-24303"},{"url":"https://github.com/python-pillow/Pillow/commit/427221ef5f19157001bf8b1ad7cfe0b905ca8c26"},{"url":"https://pillow.readthedocs.io/en/stable/releasenotes/9.0.1.html#security"},{"url":"https://github.com/python-pillow/Pillow/pull/3450"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/W4ZUXPKEX72O3E5IHBPVY5ZCPMJ4GHHV/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XR6UP2XONXOVXI4446VY72R63YRO2YTP/"},{"url":"https://github.com/advisories/GHSA-9j59-75qj-795w"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2022-168.yaml"}]}}},{"dismissedAt":null,"createdAt":"2022-03-12T00:36:36Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Pillow"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9j59-75qj-795w"},{"type":"CVE","value":"CVE-2022-24303"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-24303"},{"url":"https://github.com/python-pillow/Pillow/commit/427221ef5f19157001bf8b1ad7cfe0b905ca8c26"},{"url":"https://pillow.readthedocs.io/en/stable/releasenotes/9.0.1.html#security"},{"url":"https://github.com/python-pillow/Pillow/pull/3450"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/W4ZUXPKEX72O3E5IHBPVY5ZCPMJ4GHHV/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XR6UP2XONXOVXI4446VY72R63YRO2YTP/"},{"url":"https://github.com/advisories/GHSA-9j59-75qj-795w"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2022-168.yaml"}]}}},{"dismissedAt":null,"createdAt":"2022-03-12T00:36:36Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Pillow"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9j59-75qj-795w"},{"type":"CVE","value":"CVE-2022-24303"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-24303"},{"url":"https://github.com/python-pillow/Pillow/commit/427221ef5f19157001bf8b1ad7cfe0b905ca8c26"},{"url":"https://pillow.readthedocs.io/en/stable/releasenotes/9.0.1.html#security"},{"url":"https://github.com/python-pillow/Pillow/pull/3450"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/W4ZUXPKEX72O3E5IHBPVY5ZCPMJ4GHHV/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XR6UP2XONXOVXI4446VY72R63YRO2YTP/"},{"url":"https://github.com/advisories/GHSA-9j59-75qj-795w"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2022-168.yaml"}]}}},{"dismissedAt":null,"createdAt":"2022-03-18T13:30:45Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Pillow"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8vj2-vxx3-667w"},{"type":"CVE","value":"CVE-2022-22817"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-22817"},{"url":"https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#restrict-builtins-available-to-imagemath-eval"},{"url":"https://lists.debian.org/debian-lts-announce/2022/01/msg00018.html"},{"url":"https://www.debian.org/security/2022/dsa-5053"},{"url":"https://github.com/python-pillow/Pillow/commit/8531b01d6cdf0b70f256f93092caa2a5d91afc11"},{"url":"https://pillow.readthedocs.io/en/stable/releasenotes/9.0.1.html#security"},{"url":"https://github.com/advisories/GHSA-8vj2-vxx3-667w"}]}}},{"dismissedAt":null,"createdAt":"2022-03-18T13:30:45Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Pillow"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8vj2-vxx3-667w"},{"type":"CVE","value":"CVE-2022-22817"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-22817"},{"url":"https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#restrict-builtins-available-to-imagemath-eval"},{"url":"https://lists.debian.org/debian-lts-announce/2022/01/msg00018.html"},{"url":"https://www.debian.org/security/2022/dsa-5053"},{"url":"https://github.com/python-pillow/Pillow/commit/8531b01d6cdf0b70f256f93092caa2a5d91afc11"},{"url":"https://pillow.readthedocs.io/en/stable/releasenotes/9.0.1.html#security"},{"url":"https://github.com/advisories/GHSA-8vj2-vxx3-667w"}]}}},{"dismissedAt":null,"createdAt":"2022-03-18T13:30:46Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Pillow"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8vj2-vxx3-667w"},{"type":"CVE","value":"CVE-2022-22817"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-22817"},{"url":"https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#restrict-builtins-available-to-imagemath-eval"},{"url":"https://lists.debian.org/debian-lts-announce/2022/01/msg00018.html"},{"url":"https://www.debian.org/security/2022/dsa-5053"},{"url":"https://github.com/python-pillow/Pillow/commit/8531b01d6cdf0b70f256f93092caa2a5d91afc11"},{"url":"https://pillow.readthedocs.io/en/stable/releasenotes/9.0.1.html#security"},{"url":"https://github.com/advisories/GHSA-8vj2-vxx3-667w"}]}}},{"dismissedAt":null,"createdAt":"2022-04-15T20:38:06Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"minimist"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-xvch-5gv4-984h"},{"type":"CVE","value":"CVE-2021-44906"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-44906"},{"url":"https://github.com/substack/minimist/issues/164"},{"url":"https://github.com/substack/minimist/blob/master/index.js#L69"},{"url":"https://snyk.io/vuln/SNYK-JS-MINIMIST-559764"},{"url":"https://stackoverflow.com/questions/8588563/adding-custom-properties-to-a-function/20278068#20278068"},{"url":"https://github.com/Marynk/JavaScript-vulnerability-detection/blob/main/minimist%20PoC.zip"},{"url":"https://github.com/advisories/GHSA-xvch-5gv4-984h"}]}}},{"dismissedAt":null,"createdAt":"2022-04-22T21:33:41Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-2gwj-7jmv-h26r"},{"type":"CVE","value":"CVE-2022-28346"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-28346"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/apr/11/security-releases/"},{"url":"http://www.openwall.com/lists/oss-security/2022/04/11/1"},{"url":"https://lists.debian.org/debian-lts-announce/2022/04/msg00013.html"},{"url":"https://github.com/django/django/commit/93cae5cb2f9a4ef1514cf1a41f714fef08005200"},{"url":"https://github.com/advisories/GHSA-2gwj-7jmv-h26r"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-190.yaml"},{"url":"https://security.netapp.com/advisory/ntap-20220609-0002/"}]}}},{"dismissedAt":null,"createdAt":"2022-04-22T21:33:41Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-2gwj-7jmv-h26r"},{"type":"CVE","value":"CVE-2022-28346"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-28346"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/apr/11/security-releases/"},{"url":"http://www.openwall.com/lists/oss-security/2022/04/11/1"},{"url":"https://lists.debian.org/debian-lts-announce/2022/04/msg00013.html"},{"url":"https://github.com/django/django/commit/93cae5cb2f9a4ef1514cf1a41f714fef08005200"},{"url":"https://github.com/advisories/GHSA-2gwj-7jmv-h26r"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-190.yaml"},{"url":"https://security.netapp.com/advisory/ntap-20220609-0002/"}]}}},{"dismissedAt":null,"createdAt":"2022-04-22T21:33:41Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-2gwj-7jmv-h26r"},{"type":"CVE","value":"CVE-2022-28346"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-28346"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/apr/11/security-releases/"},{"url":"http://www.openwall.com/lists/oss-security/2022/04/11/1"},{"url":"https://lists.debian.org/debian-lts-announce/2022/04/msg00013.html"},{"url":"https://github.com/django/django/commit/93cae5cb2f9a4ef1514cf1a41f714fef08005200"},{"url":"https://github.com/advisories/GHSA-2gwj-7jmv-h26r"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-190.yaml"},{"url":"https://security.netapp.com/advisory/ntap-20220609-0002/"}]}}},{"dismissedAt":null,"createdAt":"2022-04-22T21:33:42Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w24h-v9qh-8gxj"},{"type":"CVE","value":"CVE-2022-28347"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-28347"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/apr/11/security-releases/"},{"url":"http://www.openwall.com/lists/oss-security/2022/04/11/1"},{"url":"https://github.com/django/django/commit/6723a26e59b0b5429a0c5873941e01a2e1bdbb81"},{"url":"https://github.com/advisories/GHSA-w24h-v9qh-8gxj"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-191.yaml"}]}}},{"dismissedAt":null,"createdAt":"2022-04-22T21:33:42Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w24h-v9qh-8gxj"},{"type":"CVE","value":"CVE-2022-28347"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-28347"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/apr/11/security-releases/"},{"url":"http://www.openwall.com/lists/oss-security/2022/04/11/1"},{"url":"https://github.com/django/django/commit/6723a26e59b0b5429a0c5873941e01a2e1bdbb81"},{"url":"https://github.com/advisories/GHSA-w24h-v9qh-8gxj"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-191.yaml"}]}}},{"dismissedAt":null,"createdAt":"2022-04-22T21:33:42Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w24h-v9qh-8gxj"},{"type":"CVE","value":"CVE-2022-28347"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-28347"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security/"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2022/apr/11/security-releases/"},{"url":"http://www.openwall.com/lists/oss-security/2022/04/11/1"},{"url":"https://github.com/django/django/commit/6723a26e59b0b5429a0c5873941e01a2e1bdbb81"},{"url":"https://github.com/advisories/GHSA-w24h-v9qh-8gxj"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-191.yaml"}]}}},{"dismissedAt":null,"createdAt":"2022-05-24T22:59:01Z","securityVulnerability":{"severity":"HIGH","package":{"name":"pyjwt"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-ffqj-6fqr-9h24"},{"type":"CVE","value":"CVE-2022-29217"}],"references":[{"url":"https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-29217"},{"url":"https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc"},{"url":"https://github.com/jpadilla/pyjwt/releases/tag/2.4.0"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO/"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/pyjwt/PYSEC-2022-202.yaml"},{"url":"https://github.com/advisories/GHSA-ffqj-6fqr-9h24"}]}}},{"dismissedAt":null,"createdAt":"2022-05-24T22:59:01Z","securityVulnerability":{"severity":"HIGH","package":{"name":"pyjwt"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-ffqj-6fqr-9h24"},{"type":"CVE","value":"CVE-2022-29217"}],"references":[{"url":"https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-29217"},{"url":"https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc"},{"url":"https://github.com/jpadilla/pyjwt/releases/tag/2.4.0"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO/"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/pyjwt/PYSEC-2022-202.yaml"},{"url":"https://github.com/advisories/GHSA-ffqj-6fqr-9h24"}]}}},{"dismissedAt":null,"createdAt":"2022-05-24T22:59:01Z","securityVulnerability":{"severity":"HIGH","package":{"name":"pyjwt"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-ffqj-6fqr-9h24"},{"type":"CVE","value":"CVE-2022-29217"}],"references":[{"url":"https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-29217"},{"url":"https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc"},{"url":"https://github.com/jpadilla/pyjwt/releases/tag/2.4.0"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX/"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO/"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/pyjwt/PYSEC-2022-202.yaml"},{"url":"https://github.com/advisories/GHSA-ffqj-6fqr-9h24"}]}}}]},"grade":"E"}]}